version: "3.9"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    command: npm run start
    volumes:
      - ./client:/app/client
    ports:
      - "3000:3000"
